### ISSUE TITLE
Unable to run GroovyScript 1.0.1 on Dedicated Server

### ISSUE THREAD

**Issue by chairclr** [CleanroomMC/GroovyScript#170]
Running a server with GroovyScript 1.0.1 causes an exception
 
```
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String;
    at com.cleanroommc.groovyscript.gameobjects.GameObjectHandlerManager.init(GameObjectHandlerManager.java:109)
    at com.cleanroommc.groovyscript.GroovyScript.initializeGroovyPreInit(GroovyScript.java:158)
    at net.minecraftforge.fml.common.LoadController.handler$zbk000$preInit(LoadController.java:1518)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
    at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.NoSuchMethodError: net.minecraft.creativetab.CreativeTabs.func_78013_b()Ljava/lang/String;
    at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
    at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
    at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
    at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
    at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
    at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
    ... 10 more
```

Here's the full crash report:
[crash-2024-06-04_13.26.05-server.txt](https://github.com/user-attachments/files/15568221/crash-2024-06-04_13.26.05-server.txt)

This pack is able to run fine on the client alone, but does not work on the server

Forge Version: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
Java Information: Java is OpenJDK 64-Bit Server VM, version 1.8.0_412, running on Linux:amd64:6.9.1-arch1-1, installed at /usr/lib/jvm/java-8-openjdk/jre

This is the likely offending line: https://github.com/CleanroomMC/GroovyScript/blob/3de1eb28215baef3e18cce41acfea44de79edf76/src/main/java/com/cleanroommc/groovyscript/gameobjects/GameObjectHandlerManager.java#L111

**Comment by brachy84** [comment]
Fixed [here](https://github.com/CleanroomMC/GroovyScript/commit/9f793ffa7d9ec64e7e66b1cc39a00a99c042347f)
