### ISSUE TITLE
IE machines (Crusher, Arc Furnace, maybe more?) and oredicted inputs

### ISSUE THREAD

**Issue by Wizzerinus** [CleanroomMC/GroovyScript#195]
second issue in two days, man I really should touch up on the IE compat.

so IE crusher can accept OreDicted inputs:
![image](https://github.com/CleanroomMC/GroovyScript/assets/52964431/6077e128-281e-461d-a8c2-956f3910bd9e)

but GrS cannot accept them:
```
mods.immersiveengineering.crusher.recipeBuilder()
    .input(ore("sandstone"))
    .output(item("minecraft:sand") * 2)
    .secondaryOutput(item("thermalfoundation:material", 772), 0.5)
    .register()
```

With this traceback:
```
	java.lang.RuntimeException: Recipe Ingredients must always be ItemStack, Item, Block, List<ItemStack>, String (OreDictionary name) or FluidStack; OreDictIngredient{ logWood } * 1 is invalid
		at blusunrize.immersiveengineering.api.ApiUtils.createIngredientStack(ApiUtils.java:842)
		at blusunrize.immersiveengineering.api.ApiUtils.createIngredientStack(ApiUtils.java:847)
		at blusunrize.immersiveengineering.api.crafting.CrusherRecipe.<init>(CrusherRecipe.java:45)
		at com.cleanroommc.groovyscript.compat.mods.immersiveengineering.Crusher$RecipeBuilder.register(Crusher.java:154)
		at com.cleanroommc.groovyscript.compat.mods.immersiveengineering.Crusher$RecipeBuilder.register(Crusher.java:107)
		at classes.CrusherHelper$CrusherHelperBuilder.register(CrusherHelper.groovy:44)
```

**Comment by Wizzerinus** [comment]
Happens with Arc Furnace too. I suspect it just happens with a bunch of things then
