### ISSUE TITLE
Three-way incompatibility makes `/gs hand` command error out (GrS + DummyCore + VintageFix)

### ISSUE THREAD

**Issue by Wizzerinus** [CleanroomMC/GroovyScript#213]
After a hour of trial and error, I've reduced the set of required mods to the following:
```
Mixin Booter 9.1
GroovyScript 1.1.2
Dummy Core Unofficial 2.4.112.5
Vintage Fix 0.5.0
---
Universal Tweaks 1.11.0 (optional, triggers without it)
ConfigAnytime 3.0 (if UT is installed)
```

With these mods installed, attempting to `/gs hand` any item (I tried with oak leaves) triggers an error and the client says "Unknown error when executing the command":

```
java.lang.ClassCastException: net.minecraft.creativetab.CreativeTabs$2 cannot be cast to com.cleanroommc.groovyscript.core.mixin.CreativeTabsAccessor
	at com.cleanroommc.groovyscript.helper.ingredient.GroovyScriptCodeConverter.asGroovyCode(GroovyScriptCodeConverter.java:162) ~[GroovyScriptCodeConverter.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.InfoParserCreativeTab.text(InfoParserCreativeTab.java:24) ~[InfoParserCreativeTab.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.InfoParserCreativeTab.text(InfoParserCreativeTab.java:8) ~[InfoParserCreativeTab.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.GenericInfoParser.copyText(GenericInfoParser.java:119) ~[GenericInfoParser.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.GenericInfoParser.information(GenericInfoParser.java:143) ~[GenericInfoParser.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.GenericInfoParser.iterate(GenericInfoParser.java:154) ~[GenericInfoParser.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.GenericInfoParser.add(GenericInfoParser.java:168) ~[GenericInfoParser.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.GenericInfoParser.add(GenericInfoParser.java:177) ~[GenericInfoParser.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.InfoParserCreativeTab.parse(InfoParserCreativeTab.java:32) ~[InfoParserCreativeTab.class:?]
	at com.cleanroommc.groovyscript.compat.vanilla.command.infoparser.GenericInfoParser.parse(GenericInfoParser.java:213) ~[GenericInfoParser.class:?]
	at com.cleanroommc.groovyscript.api.infocommand.InfoParserPackage.lambda$parse$0(InfoParserPackage.java:178) ~[InfoParserPackage.class:?]
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_412]
	at com.cleanroommc.groovyscript.api.infocommand.InfoParserPackage.parse(InfoParserPackage.java:178) ~[InfoParserPackage.class:?]
	at com.cleanroommc.groovyscript.command.BaseInfoCommand.func_184881_a(BaseInfoCommand.java:145) ~[BaseInfoCommand.class:?]
	at net.minecraftforge.server.command.CommandTreeBase.func_184881_a(CommandTreeBase.java:164) ~[CommandTreeBase.class:?]
	at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:119) [bj.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:91) [bj.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_412]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_412]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:1817) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_412]
```

**Comment by brachy84** [comment]
Can not reproduce

**Comment by Wizzerinus** [comment]
Will re-test this the next week

**Comment by Wizzerinus** [comment]
Reproduced with a clean Forge 2860 install with updated mod versions (used `/gs looking`):
```
MixinBooter 9.3
GroovyScript 1.1.3
VintageFix 0.5.1
```
No config changes or anything as that's a clean install. Also reproduced with Forge 2847 as I believe that's what dev env uses, just in case.

**Comment by Wizzerinus** [comment]
new info on this:

```
...
[22:05:04] [main/INFO] [org.spongepowered.asm.service.mojang.MixinServiceLaunchWrapper]: A re-entrant transformer '$wrapper.DummyCore.ASM.DCASMManager' was detected and will no longer process meta class data
[22:05:04] [main/INFO] [EnderCore ASM]: Transforming Class [net.minecraft.client.renderer.RenderItem], Method [func_180453_a, func_184391_a]
[22:05:04] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.client.renderer.RenderItem Finished.
....

[22:05:04] [main/ERROR] [mixin]: Critical problem: mixin.groovyscript.json:CreativeTabsAccessor from owner groovyscript target net.minecraft.creativetab.CreativeTabs was loaded too early.

...
[22:05:05] [main/INFO] [EnderCore ASM]: Transforming Class [net.minecraft.entity.item.EntityItemFrame], Method [func_184230_a]
[22:05:05] [main/INFO] [EnderCore ASM]: Transforming net.minecraft.entity.item.EntityItemFrame Finished.
[22:05:05] [main/INFO] [thaumicaugmentationcore]: Successfully transformed class net.minecraft.world.WorldServer
[22:05:05] [main/INFO] [thaumicaugmentationcore]: Successfully transformed class net.minecraft.item.ItemSpade
...
```

I don't know whether it's related but it's the same class present in the error traceback!
