### ISSUE TITLE
Crash on startup w. Ender IO

### ISSUE THREAD

**Issue by Shazuli** [CleanroomMC/GroovyScript#67]
***Hi***

The game crashes on startup with [Ender IO](https://legacy.curseforge.com/minecraft/mc-mods/ender-io-base).

### Mods
* GroovyScript 0.5.0
* [!mixinbooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) 8.2
* [Ender IO](https://legacy.curseforge.com/minecraft/mc-mods/ender-io-base) 5.3.70
* [EnderCore](https://legacy.curseforge.com/minecraft/mc-mods/endercore) 1.12.2-0.5.76

<details>
  <summary>crash-2023-06-25_15.40.45-client.txt</summary>

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  GroovyScript-Core (groovyscript-0.5.0.jar)
  MixinBooter (!mixinbooter-8.2.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 6/25/23 3:40 PM
Description: Initializing game

com.google.common.util.concurrent.ExecutionError: java.lang.ExceptionInInitializerError
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:40)
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:49)
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35)
	at com.cleanroommc.groovyscript.GroovyScript.initializeGroovyPreInit(GroovyScript.java:138)
	at net.minecraftforge.fml.common.LoadController.handler$zzf000$groovyscript_0_5_0$preInit(LoadController.java:1017)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.ExceptionInInitializerError
	at crazypants.enderio.base.config.config.PersonalConfig.<clinit>(PersonalConfig.java:11)
	at crazypants.enderio.base.loot.LootManager.onLootTableLoad(LootManager.java:94)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_53_LootManager_onLootTableLoad_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:775)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1186)
	at net.minecraft.world.storage.loot.LootTableManager$Loader.func_186518_c(LootTableManager.java:156)
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72)
	at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
	... 29 more
Caused by: java.lang.NullPointerException
	at crazypants.enderio.base.config.config.BaseConfig.<clinit>(BaseConfig.java:23)
	... 43 more

(MixinBooter) Mixins in Stacktrace:
	net.minecraft.client.Minecraft:
		com.cleanroommc.groovyscript.core.mixin.DefaultResourcePackAccessor (mixin.groovyscript.json) [groovyscript-0.5.0.jar]
	net.minecraftforge.fml.common.LoadController:
		com.cleanroommc.groovyscript.core.mixin.LoaderControllerMixin (mixin.groovyscript.json) [groovyscript-0.5.0.jar]
		zone.rong.mixinbooter.mixin.LoadControllerMixin (mixin.mixinbooter.init.json) [unknown]

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2215)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
	at net.minecraft.world.storage.loot.LootTableManager.func_186521_a(LootTableManager.java:40)
	at net.minecraft.world.storage.loot.LootTableManager.func_186522_a(LootTableManager.java:49)
	at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35)
	at com.cleanroommc.groovyscript.GroovyScript.initializeGroovyPreInit(GroovyScript.java:138)
	at net.minecraftforge.fml.common.LoadController.handler$zzf000$groovyscript_0_5_0$preInit(LoadController.java:1017)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 6.3.5-2-MANJARO
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1669627632 bytes (1592 MB) / 3168796672 bytes (3022 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 2 total; -Xms2048m -Xmx8064m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version       | Source                                  | Signature                                |
	|:----- |:-------------- |:------------- |:--------------------------------------- |:---------------------------------------- |
	| LC    | minecraft      | 1.12.2        | minecraft.jar                           | None                                     |
	| LC    | mcp            | 9.42          | minecraft.jar                           | None                                     |
	| LC    | FML            | 8.0.99.99     | forge-1.12.2-14.23.5.2859-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge          | 14.23.5.2859  | forge-1.12.2-14.23.5.2859-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | beyond_reality | 2.1.0         | .minecraft                              | None                                     |
	| LC    | mixinbooter    | 8.2           | minecraft.jar                           | None                                     |
	| LC    | endercore      | 1.12.2-0.5.76 | EnderCore-1.12.2-0.5.76.jar             | None                                     |
	| LC    | enderio        | 5.3.70        | EnderIO-base-1.12.2-5.3.70.jar          | None                                     |
	| LC    | enderiobase    | 5.3.70        | EnderIO-base-1.12.2-5.3.70.jar          | None                                     |
	| LC    | groovyscript   | 0.5.0         | groovyscript-0.5.0.jar                  | None                                     |

	Loaded coremods (and transformers): 
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
GroovyScript-Core (groovyscript-0.5.0.jar)
  
MixinBooter (!mixinbooter-8.2.jar)
  
	GL info: ' Vendor: 'AMD' Version: '4.6 (Compatibility Profile) Mesa 23.0.3' Renderer: 'AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.5-2-MANJARO)'
	Ender IO: No known problems detected.
	Authlib is : /home/simon/.local/share/multimc/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Launched Version: 1.12.2
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 6700 XT (navi22, LLVM 15.0.7, DRM 3.52, 6.3.5-2-MANJARO) GL version 4.6 (Compatibility Profile) Mesa 23.0.3, AMD
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
```

**Comment by brachy84** [comment]
Fixed [here](https://github.com/CleanroomMC/GroovyScript/commit/1102601c8223f8c4719f25a879d809af3aadafaa)
