### ISSUE TITLE
crash with TFC

### ISSUE THREAD

**Issue by blakpsykozz27** [CleanroomMC/GroovyScript#82]
---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// You're mean.

Time: 2023-08-10 18:33:10 CEST
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from GroovyScript (groovyscript)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2217)
    at com.google.common.cache.LocalCache.get(LocalCache.java:4154)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
    at net.minecraft.world.storage.loot.LootTableManager.getLootTableFromLocation(LootTableManager.java:40)
    at net.minecraft.world.storage.loot.LootTableManager.reloadLootTables(LootTableManager.java:49)
    at net.minecraft.world.storage.loot.LootTableManager.<init>(LootTableManager.java:35)
    at com.cleanroommc.groovyscript.GroovyScript.onInit(GroovyScript.java:120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4101)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
    at org.multimc.EntryPoint.listen(EntryPoint.java:143)
    at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
    at com.google.common.cache.LocalCache.get(LocalCache.java:4153)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153)
    at net.minecraft.world.storage.loot.LootTableManager.getLootTableFromLocation(LootTableManager.java:40)
    at net.dries007.tfc.objects.LootTablesTFC.onLootTableLoad(LootTablesTFC.java:128)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_209_LootTablesTFC_onLootTableLoad_LootTableLoadEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:775)
    at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:1186)
    at net.minecraft.world.storage.loot.LootTableManager$Loader.loadBuiltinLootTable(LootTableManager.java:156)
    at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:72)
    at net.minecraft.world.storage.loot.LootTableManager$Loader.load(LootTableManager.java:53)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)
    ... 56 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_381, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 5509058408 bytes (5253 MB) / 7397703680 bytes (7055 MB) up to 11304173568 bytes (10780 MB)
  JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx12128m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.14 Powered by Forge 14.23.5.2860 32 mods loaded, 32 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                  | Version                            | Source                                                     | Signature                                |
       |:----- |:------------------- |:---------------------------------- |:---------------------------------------------------------- |:---------------------------------------- |
       | LCHI  | minecraft           | 1.12.2                             | minecraft.jar                                              | None                                     |
       | LCHI  | mcp                 | 9.42                               | minecraft.jar                                              | None                                     |
       | LCHI  | FML                 | 8.0.99.99                          | forge-1.12.2-14.23.5.2860-universal.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | forge               | 14.23.5.2860                       | forge-1.12.2-14.23.5.2860-universal.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHI  | placeholdername     | 1.0.0                              | .minecraft                                                 | None                                     |
       | LCHI  | mixinbooter         | 8.3                                | minecraft.jar                                              | None                                     |
       | LCHI  | opencomputers|core  | 1.7.5.192                          | minecraft.jar                                              | None                                     |
       | LCHI  | appliedenergistics2 | rv6-stable-7-extended_life-v0.53.4 | appliedenergistics2-rv6-stable-7-extended_life-v0.53.4.jar | None                                     |
       | LCHI  | baubles             | 1.5.2                              | Baubles-1.12-1.5.2.jar                                     | None                                     |
       | LCHI  | crafttweaker        | 4.1.20                             | CraftTweaker2-1.12-4.1.20.684.jar                          | None                                     |
       | LCHI  | jei                 | 4.24.0                             | HadEnoughItems_1.12.2-4.24.0.jar                           | None                                     |
       | LCHI  | loliasm             | 5.14                               | censoredasm5.14.jar                                        | None                                     |
       | LCHI  | codechickenlib      | 3.2.3.358                          | CodeChickenLib-1.12.2-3.2.3.358-universal.jar              | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHI  | ctgui               | 1.0.0                              | CraftTweaker2-1.12-4.1.20.684.jar                          | None                                     |
       | LCHI  | crafttweakerjei     | 2.0.3                              | CraftTweaker2-1.12-4.1.20.684.jar                          | None                                     |
       | LCHI  | forestry            | 5.8.2.422                          | forestry_1.12.2-5.8.2.422.jar                              | None                                     |
       | LCHE  | groovyscript        | 0.6.0                              | groovyscript-0.6.0.jar                                     | None                                     |
       | LCH   | gregtech            | 2.7.2-beta                         | gregtech-1.12.2-2.7.2-beta.jar                             | None                                     |
       | LCH   | devtech             | 2.1.4                              | devtech-2.1.4.jar                                          | None                                     |
       | LCH   | forgelin            | 1.8.4                              | Forgelin-1.8.4.jar                                         | None                                     |
       | LCH   | exnihilocreatio     | 1.12.2-0.4.7.1                     | exnihilocreatio-1.12.2-0.4.7.1.jar                         | None                                     |
       | LCH   | extrautils2         | 1.0                                | extrautils2-1.12-1.9.9.jar                                 | None                                     |
       | LCH   | geckolib3           | 3.0.30                             | geckolib-forge-1.12.2-3.0.30.jar                           | None                                     |
       | LCH   | gfarm               | 0.1.8                              | gfarm-0.1.8.jar                                            | None                                     |
       | LCH   | gcym                | 1.2.4                              | GregicalityMultiblocks-1.2.4.jar                           | None                                     |
       | LCH   | gregification       | @VERSION@                          | Gregification-1.12.2-0.0.1.jar                             | None                                     |
       | LCH   | gregtechfoodoption  | @VERSION@                          | gregtechfoodoption-1.9.3.1.jar                             | None                                     |
       | LCH   | modularmachinery    | 1.11.1                             | ModularMachinery-CE-1.12.2-1.11.1-r24.jar                  | None                                     |
       | LCH   | multiblocktweaker   | 1.12.2-stable-gtceu-1.9.0          | multiblocktweaker-1.12.2-stable-gtceu-1.9.0.jar            | None                                     |
       | LCH   | opencomputers       | 1.7.5.192                          | OpenComputers-MC1.12.2-1.7.5.192.jar                       | None                                     |
       | LCH   | tfc                 | 1.7.23.181                         | TerraFirmaCraft-MC1.12.2-1.7.23.181.jar                    | None                                     |
       | LCH   | thaumcraft          | 6.1.BETA26                         | Thaumcraft-1.12.2-6.1.BETA26.-.fixed.jar                   | None                                     |
  Loaded coremods (and transformers): MixinBooter (!mixinbooter-8.3.jar)
                                        
                                      GroovyScript-Core (groovyscript-0.6.0.jar)
                                        
                                      TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
                                        li.cil.oc.common.asm.ClassTransformer
                                      ForgelinPlugin (Forgelin-1.8.4.jar)
                                        
                                      LoliASM (censoredasm5.14.jar)
                                        
                                      GregTechLoadingPlugin (gregtech-1.12.2-2.7.2-beta.jar)
                                        gregtech.asm.GregTechTransformer
                                      Gregification (Gregification-1.12.2-0.0.1.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 536.67' Renderer: 'NVIDIA GeForce GTX 1080/PCIe/SSE2'
  AE2 Version: stable rv6-stable-7-extended_life-v0.53.4 for Forge 14.23.5.2847
  Suspected Mods: GroovyScript (groovyscript), Forge Mod Loader (FML), Minecraft Forge (forge), TerraFirmaCraft (tfc)
  Launched Version: 1.12.2
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 4.6.0 NVIDIA 536.67, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 16x Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz

**Comment by blakpsykozz27** [comment]
groovyscript-0.6.0
TerraFirmaCraft-MC1.12.2-1.7.23.181

**Comment by brachy84** [comment]
im about to yeet the loot compat ffs

**Comment by brachy84** [comment]
can you try 0.6.1 pls?

**Comment by blakpsykozz27** [comment]
Where is the version ?

**Comment by blakpsykozz27** [comment]
it works thanks

**Comment by brachy84** [comment]
https://github.com/CleanroomMC/GroovyScript/releases/tag/v0.6.1

**Comment by blakpsykozz27** [comment]
it works with 0.6.1
